<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1637760362388' stop='1637760371938'>
    <name>Verify Login Scenarios on Saxobank React Native Mobile App</name>
    <title>Verify Login Scenarios on Saxobank React Native Mobile App</title>
    <test-cases>
        <test-case start='1637760362389' status='broken' stop='1637760371805'>
            <name>User should not be able to login using wrong credentials to Saxobank Mobile App</name>
            <title>User should not be able to login using wrong credentials to Saxobank Mobile App</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='device' value='emulator-5554-11'/>
            </parameters>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='b0b952f9-af20-484f-ae4e-12d4088b76c4-attachment.png' type='image/png' size='201806'/>
            </attachments>
            <failure>
                <message>Invalid Chai property: toExist. Did you mean "exist"?</message>
                <stack-trace>Error: Invalid Chai property: toExist. Did you mean "exist"?
                    at Object.proxyGetter [as get] (E:\Projects\MobileAutomationTest\node_modules\chai\lib\chai\utils\proxify.js:75:17)
                    at Context.&lt;anonymous> (E:\Projects\MobileAutomationTest\test\specs\example.e2e.js:21:15)
                    at Context.executeSync (E:\Projects\MobileAutomationTest\node_modules\@wdio\sync\build\index.js:38:22)
                    at E:\Projects\MobileAutomationTest\node_modules\@wdio\sync\build\index.js:69:73</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>