<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1639130720684' stop='1639130720694'>
    <name>Verify Login Scenarios on Saxobank React Native Mobile App</name>
    <title>Verify Login Scenarios on Saxobank React Native Mobile App</title>
    <test-cases>
        <test-case start='1639130720684' status='broken' stop='1639130720692'>
            <name>User should not be able to login using wrong credentials to Saxobank Mobile App</name>
            <title>User should not be able to login using wrong credentials to Saxobank Mobile App</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='device' value='Pixel 3 9-9'/>
            </parameters>
            <steps/>
            <attachments/>
            <failure>
                <message>driver.contexts is not a function</message>
                <stack-trace>TypeError: driver.contexts is not a function
                    at Context.&lt;anonymous> (E:\Projects\Test-mobile\MobileAutomationTest\test\specs\example.e2e.js:8:3)
                    at Context.executeAsync (E:\Projects\Test-mobile\MobileAutomationTest\node_modules\@wdio\utils\build\shim.js:325:27)
                    at Context.testFrameworkFnWrapper (E:\Projects\Test-mobile\MobileAutomationTest\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:45:32)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>